- name: install docker vm
  hosts: fil_cl
  gather_facts: false

  tasks:
  - name: install docker.io
    become: yes
    apt:
      name: docker.io
      state: present
  - name: install docker-compose
    become: yes
    apt:
      name: docker-compose
      state: present
  - name: test docker service is running
    become: yes
    service:
      name: docker
      state: started
