- name: Install WordPress fil_cl
  hosts: fil_cl
  gather_facts: false

  tasks:
  - name: create volume for wordpress
    become: yes
    command: docker volume create --name wordpress_data
    register: debugCreateVolume
  - name: log create volume web
    debug:
     var: debugCreateVolume
  - name:  run image wordpress
    become: yes
    command:   docker run -d --name wordpress   --env WORDPRESS_DATABASE_HOST=192.168.5.10  --env ALLOW_EMPTY_PASSWORD=yes   --env WORDPRESS_DATABASE_USER=bn_wordpress   --env WORDPRESS_DATABASE_PASSWORD=bitnami   --env WORDPRESS_DATABASE_NAME=bitnami_wordpress   --network host   --volume wordpress_data:/bitnami/wordpress   bitnami/wordpress:latest   
    register: debugRunWp
  - name: log run web
    debug:
     var: debugRunWp
