- name: Install WP, DB
  hosts: wp
  gather_facts: false
  become: yes

  tasks:
  - name: create network
    command: docker network create wordpress-network
  - name: create volume for db
    command: docker volume create --name mariadb_data
  - name:  run image mariadb
    command: docker run -d --name mariadb --env ALLOW_EMPTY_PASSWORD=yes --env MARIADB_USER=bn_wordpress --env MARIADB_PASSWORD=bitnami --env MARIADB_DATABASE=bitnami_wordpress --network wordpress-network --volume mariadb_data:/bitnami/mariadb bitnami/mariadb:latest
  - name: create volume for web
    command: docker volume create --name wordpress_data
  - name:  run image wordpress
    command: docker run -d --name wordpress  -p 8080:8080 -p 8443:8443 --env ALLOW_EMPTY_PASSWORD=yes --env WORDPRESS_DATABASE_USER=bn_wordpress  --env WORDPRESS_DATABASE_PASSWORD=bitnami  --env WORDPRESS_DATABASE_NAME=bitnami_wordpress --network wordpress-network --volume wordpress_data:/bitnami/wordpress  bitnami/wordpress:late